[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-audit --engine-strict=false"]

[phases.build]
cmds = ["node scripts/copy-assets.js"]

[start]
cmd = "node dist/index.js"
