import { Request, Response } from 'express';
import { winstonLogger } from '../middleware/logger';
import { llmService } from '../services/llmService';
import { pnrTrackingService } from '../services/pnrTrackingService';
import { providerConfigService } from '../services/providerConfigService';
import { rapidApiService } from '../services/rapidApiService';
import { trainService } from '../services/trainService';
import { normalizeRawPnr } from '../utils/pnrNormalizer';

export class PnrController {
  private isValidPnrResponse(rawStatus: any): boolean {
    if (!rawStatus || typeof rawStatus !== 'object') return false;
    if (rawStatus.success === false || rawStatus.status === false || rawStatus.error) return false;

    const pnrKeys = [
      'pnr',
      'PNR',
      'Pnr',
      'pnrNo',
      'pnrNumber',
      'PNR_No',
      'PNRNumber',
      'PnrNo'
    ];

    for (const key of pnrKeys) {
      if (rawStatus[key] || rawStatus.data?.[key]) return true;
    }

    if (Array.isArray(rawStatus.passengers) && rawStatus.passengers.length > 0) return true;
    if (Array.isArray(rawStatus.data?.passengers) && rawStatus.data.passengers.length > 0) return true;
    if (rawStatus.trainNumber || rawStatus.train?.number || rawStatus.data?.trainNumber || rawStatus.data?.train?.number) return true;

    return false;
  }

  private buildPnrFallback(pnr: string) {
    winstonLogger.warn(`[PNR_UNAVAILABLE] Both providers returned no data for PNR ${pnr}. Returning honest error.`);
    return {
      success: false,
      error: 'pnr_unavailable',
      message: 'This PNR could not be retrieved. It may be flushed, invalid, or not yet generated by IRCTC. Please verify the PNR on the official IRCTC website.',
      data_source: 'unavailable',
      data: null
    };
  }

  private parseJourneyDate(dateStr: string): Date | null {
    if (!dateStr || dateStr === 'N/A' || typeof dateStr !== 'string') return null;
    
    const clean = dateStr.trim();
    
    // Check for DD/MM/YY or DD/MM/YYYY formats
    const slashParts = clean.split('/');
    if (slashParts.length === 3) {
      const day = parseInt(slashParts[0], 10);
      const month = parseInt(slashParts[1], 10) - 1; // 0-indexed month
      
      const yearAndTime = slashParts[2].trim().split(/\s+/);
      let year = parseInt(yearAndTime[0], 10);
      if (year < 100) {
        year += 2000;
      }
      
      let hours = 0;
      let minutes = 0;
      
      if (yearAndTime.length >= 2) {
        const timeParts = yearAndTime[1].split(':');
        hours = parseInt(timeParts[0], 10);
        minutes = parseInt(timeParts[1] || '0', 10);
        
        const ampm = yearAndTime[2]?.toUpperCase();
        if (ampm === 'PM' && hours < 12) {
          hours += 12;
        } else if (ampm === 'AM' && hours === 12) {
          hours = 0;
        }
      }
      
      const parsedDate = new Date(year, month, day, hours, minutes);
      if (!isNaN(parsedDate.getTime())) {
        return parsedDate;
      }
    }
    
    // Split on hyphens (YYYY-MM-DD or DD-MM-YYYY)
    const hyphenParts = clean.split('-');
    if (hyphenParts.length === 3) {
      if (hyphenParts[0].length === 4) {
        // YYYY-MM-DD
        const year = parseInt(hyphenParts[0], 10);
        const month = parseInt(hyphenParts[1], 10) - 1;
        const day = parseInt(hyphenParts[2], 10);
        const d = new Date(year, month, day);
        if (!isNaN(d.getTime())) return d;
      } else {
        // DD-MM-YYYY or DD-MM-YY
        const day = parseInt(hyphenParts[0], 10);
        const month = parseInt(hyphenParts[1], 10) - 1;
        let year = parseInt(hyphenParts[2], 10);
        if (year < 100) year += 2000;
        const d = new Date(year, month, day);
        if (!isNaN(d.getTime())) return d;
      }
    }

    const d = new Date(clean);
    if (!isNaN(d.getTime())) {
      return d;
    }
    
    return null;
  }

  // ── Phase 1: Confidence Label Mapping ─────────────────────────────────
  private getConfidenceLabel(prob: number | null, statusType: string): string {
    if (statusType === 'CNF') return 'Confirmed \u2013 Enjoy Your Journey';
    if (statusType === 'RAC') return 'Strong Chance \u2013 RAC Seat Confirmed';
    if (prob === null) return 'Prediction Unavailable';
    if (prob >= 75) return 'Strong Confirmation Chance';
    if (prob >= 50) return 'Moderate Confirmation Chance';
    if (prob >= 30) return 'Low Confirmation Chance';
    return 'Very Low Confirmation Chance';
  }

  getStatus = async (req: Request, res: Response) => {
    // ... existing getStatus logic ...
    const { pnr } = req.params;
    const sessionId = req.headers['x-session-id'] as string;

    if (!pnr || pnr.length !== 10) {
      return res.status(400).json({ error: 'Valid 10-digit PNR is required' });
    }

    try {
      const userId = req.headers['x-user-id'] as string || null;
      const deviceId = req.headers['x-device-id'] as string;
      const betaCode = req.headers['x-beta-code'] as string;
      const { authService } = require('../services/authService');

      if (userId || betaCode) {
        // Authenticated user or beta - check usage limits
        const canUse = await authService.canUseFeature(userId, 'pnr', betaCode);
        if (!canUse) {
          return res.status(403).json({
            success: false,
            error: "limit_exceeded",
            message: "Upgrade to continue"
          });
        }

        // Increment usage count
        await authService.incrementUsage(userId, 'pnr', betaCode);
      } else {
        // Guest user
      }
      const { stationService } = require('../services/stationService');
      const { irctcService } = require('../services/irctcService');

      let rawStatus: any = null;
      let pnrSource = "RAPIDAPI";

      // 1. Try IRCTC (Primary)
      const irctcGuard = await providerConfigService.isProviderEnabled('IRCTC');
      if (irctcGuard.enabled) {
        try {
          winstonLogger.info('[PNR_CONTROLLER] Trying IRCTC for PNR lookup');
          rawStatus = await irctcService.checkPNRStatus(pnr);
          winstonLogger.info(`[PNR_IRCTC_DEBUG] rawStatus: ${JSON.stringify(rawStatus)}`);

          if (rawStatus && this.isValidPnrResponse(rawStatus)) {
            pnrSource = "IRCTC";
            winstonLogger.info(`[PNR_SUCCESS] IRCTC found ${pnr}`);
          } else {
            winstonLogger.warn(`[PNR_IRCTC_EMPTY] IRCTC returned success but insufficient PNR payload for ${pnr}`);
            rawStatus = null; // Force fallback
          }
        } catch (e) {
          winstonLogger.warn('[PNR_CONTROLLER] IRCTC PNR lookup failed, trying fallback');
        }
      } else {
        const skipLabel = (irctcGuard.reason === 'PROVIDER_UNHEALTHY' || irctcGuard.reason === 'CIRCUIT_BREAKER_BLOCKED')
          ? '[PROVIDER_SKIPPED_UNHEALTHY]'
          : '[PROVIDER_SKIPPED_DISABLED]';
        winstonLogger.info(`${skipLabel} IRCTC | Reason: ${irctcGuard.reason}`);
      }

      // 2. Try RailRadar (Secondary)
      if (!this.isValidPnrResponse(rawStatus)) {
        const rrGuard = await providerConfigService.isProviderEnabled('RAILRADAR');
        if (rrGuard.enabled) {
          try {
            winstonLogger.info('[PNR_CONTROLLER] Trying RailRadar for PNR lookup');
            const { railRadarService } = require('../services/railRadarService');
            rawStatus = await railRadarService.getPNRStatus(pnr);
            if (rawStatus && this.isValidPnrResponse(rawStatus)) {
              pnrSource = "RAILRADAR";
              winstonLogger.info(`[PNR_SUCCESS] RailRadar found ${pnr}`);
            } else {
              rawStatus = null;
            }
          } catch (e) {
            winstonLogger.warn('[PNR_CONTROLLER] RailRadar PNR lookup failed');
            rawStatus = null;
          }
        } else {
          const skipLabel = (rrGuard.reason === 'PROVIDER_UNHEALTHY' || rrGuard.reason === 'CIRCUIT_BREAKER_BLOCKED')
            ? '[PROVIDER_SKIPPED_UNHEALTHY]'
            : '[PROVIDER_SKIPPED_DISABLED]';
          winstonLogger.info(`${skipLabel} RAILRADAR | Reason: ${rrGuard.reason}`);
        }
      }

      // 3. Try RapidAPI (Tertiary)
      if (!this.isValidPnrResponse(rawStatus)) {
        const rapidGuard = await providerConfigService.isProviderEnabled('RAPIDAPI');
        if (rapidGuard.enabled) {
          try {
            winstonLogger.info('[PNR_CONTROLLER] Trying RapidAPI for PNR lookup');
            rawStatus = await rapidApiService.getPNRStatus(pnr);
            if (rawStatus && this.isValidPnrResponse(rawStatus)) {
              pnrSource = "RAPIDAPI";
            } else {
              rawStatus = null;
            }
          } catch (e) {
            winstonLogger.warn('[PNR_CONTROLLER] RapidAPI PNR lookup also failed');
            rawStatus = null;
          }
        } else {
          const skipLabel = (rapidGuard.reason === 'PROVIDER_UNHEALTHY' || rapidGuard.reason === 'CIRCUIT_BREAKER_BLOCKED')
            ? '[PROVIDER_SKIPPED_UNHEALTHY]'
            : '[PROVIDER_SKIPPED_DISABLED]';
          winstonLogger.info(`${skipLabel} RAPIDAPI | Reason: ${rapidGuard.reason}`);
        }
      }

      // 4. Try Database Cache Fallback (IRCTC Connect -> Database Cache -> Stop order)
      if (!this.isValidPnrResponse(rawStatus)) {
        winstonLogger.info("[DB_FALLBACK_USED] PNR - Using cached DB record");
        try {
          const twentyFourHoursAgo = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
          const { data: cachedDbRecord } = await require('../config/supabase').supabase
            .from('pnr_tracking')
            .select('*')
            .eq('pnr_number', pnr)
            .gte('last_updated', twentyFourHoursAgo)
            .order('last_updated', { ascending: false })
            .limit(1)
            .maybeSingle();

          if (cachedDbRecord) {
            rawStatus = {
              pnr: cachedDbRecord.pnr_number,
              boardingDay: cachedDbRecord.journey_date,
              trainName: cachedDbRecord.train_name || "Unknown Train",
              trainNumber: cachedDbRecord.train_no || "00000",
              chartStatus: cachedDbRecord.chart_status || "Chart Not Prepared",
              from: { code: cachedDbRecord.source_code || "", name: cachedDbRecord.source_name || "" },
              to: { code: cachedDbRecord.destination_code || "", name: cachedDbRecord.destination_name || "" },
              passengers: [
                {
                  passengerName: "Passenger 1",
                  bookingStatus: cachedDbRecord.current_status,
                  currentStatus: cachedDbRecord.current_status
                }
              ]
            };
            pnrSource = "DATABASE_FALLBACK";
            winstonLogger.info(`[PNR_SUCCESS] Database fallback found cached record for ${pnr}`);
          }
        } catch (dbErr: any) {
          winstonLogger.warn(`[PNR_DB_FALLBACK_FAILED] ${pnr}: ${dbErr.message}`);
        }
      }

      if (!this.isValidPnrResponse(rawStatus)) {
        winstonLogger.warn(`[PNR_FALLBACK] No live PNR available, issuing estimated response for ${pnr}`);
        
        // Log PNR failure telemetry asynchronously
        try {
          const { selfLearningService } = require('../services/selfLearningService');
          setImmediate(() => {
            selfLearningService.logPnrFailure(pnr, userId).catch(() => {});
          });
        } catch (e) {}

        return res.status(200).json(this.buildPnrFallback(pnr));
      }

      // LOG RAW RESPONSE FOR DEBUGGING
      winstonLogger.info(`[PNR RAW RESPONSE] source=${pnrSource} pnr=${pnr}: ${JSON.stringify(rawStatus)}`);

      // Normalize the raw data for mapping using our shared helper
      const normalized = normalizeRawPnr(rawStatus);

      // 0. Journey Date Expiry Validation (Issue 1)
      const journeyStr = normalized.journey_date;
      if (journeyStr && journeyStr !== 'N/A') {
        const journeyDate = this.parseJourneyDate(journeyStr);
        if (journeyDate) {
          const now = Date.now();
          const hoursSinceJourney = (now - journeyDate.getTime()) / (1000 * 60 * 60);
          if (hoursSinceJourney >= 96) {
            winstonLogger.warn(`[PNR_EXPIRED] PNR ${pnr} has expired beyond allowed window (${hoursSinceJourney.toFixed(1)}h since journey). Returning fallback.`);
            return res.status(200).json(this.buildPnrFallback(pnr));
          }
        }
      }

      // 2. Identify "Worst" Status for Prediction & Evaluate Passenger Mix
      let worstStatusType: string = 'CNF';
      let minWLPos = 999;
      let cnfCount = 0;
      let wlCount = 0;
      let racCount = 0;

      const isCnfStatus = (s: string) => {
        const upper = (s || '').toUpperCase();
        return upper.includes('CNF') || upper.includes('CONFIRM') || upper.includes('CONFIRMED') || (upper.includes('-') && !upper.includes('WL') && !upper.includes('RAC'));
      };
      const isWlStatus = (s: string) => {
        const upper = (s || '').toUpperCase();
        return upper.includes('WL') || upper.includes('WAIT');
      };
      const isRacStatus = (s: string) => {
        const upper = (s || '').toUpperCase();
        return upper.includes('RAC');
      };

      const cleanedPassengers = normalized.passengers.map((p) => {
        const rawStatusText = p.current_status.toUpperCase();
        const rawSeatText = p.current_status.toUpperCase();

        if (isCnfStatus(p.current_status)) {
          cnfCount++;
        } else if (isWlStatus(p.current_status)) {
          wlCount++;
          worstStatusType = 'WL';
          const pos = parseInt(rawSeatText.match(/\d+/)?.[0] || rawStatusText.match(/\d+/)?.[0] || "100");
          if (pos < minWLPos) minWLPos = pos;
        } else if (isRacStatus(p.current_status)) {
          racCount++;
          if (worstStatusType !== 'WL') worstStatusType = 'RAC';
        } else {
          // Fallback if not matching explicitly
          if (rawStatusText.includes('WL') || rawStatusText.includes('WAITLIST') || rawSeatText.includes('WL')) {
            wlCount++;
            worstStatusType = 'WL';
            const pos = parseInt(rawSeatText.match(/\d+/)?.[0] || rawStatusText.match(/\d+/)?.[0] || "100");
            if (pos < minWLPos) minWLPos = pos;
          } else if (rawStatusText.includes('RAC') && worstStatusType !== 'WL') {
            racCount++;
            worstStatusType = 'RAC';
          } else {
            cnfCount++;
          }
        }

        return {
          name: p.name,
          booking_status: p.booking_status,
          current_status: p.current_status
        };
      });

      const totalPassengers = cleanedPassengers.length;
      const isPartiallyConfirmed = cnfCount > 0 && cnfCount < totalPassengers;

      // 3. AI Prediction Logic (Strict Thresholds + LLM)
      let probability = "100%";
      let predictionText = "Confirmed";
      let advice = "Enjoy your journey!";
      let explanation = '';
      let showPrediction = false;

      let predictionSource = "SYSTEM"; // Default for CNF/RAC

      const isChartPrepared = normalized.chart_status &&
        normalized.chart_status.toUpperCase().includes('PREPARED') &&
        !normalized.chart_status.toUpperCase().includes('NOT PREPARED');

      const isConfirmed = cnfCount === totalPassengers;

      if (isChartPrepared) {
        if (isConfirmed) {
          predictionText = "Confirmed";
          advice = "All passengers confirmed.";
        } else if (isPartiallyConfirmed) {
          predictionText = "Partially Confirmed";
          advice = `Chart Prepared. ${cnfCount} of ${totalPassengers} passengers are confirmed. Remaining passengers are waitlisted.`;
        } else {
          predictionText = worstStatusType === 'RAC' ? "RAC (Seat Allocated)" : "Not Confirmed (WL)";
          advice = "No passengers confirmed.";
        }
      } else if (isPartiallyConfirmed || worstStatusType === 'WL' || worstStatusType === 'RAC') {
        showPrediction = true;
        
        // Resolve travel details using the passenger with worst waitlist status (P1 multi-passenger fix)
        const targetPassenger = cleanedPassengers.find(p => {
          const s = (p.current_status || p.booking_status || '').toUpperCase();
          return isWlStatus(s) || isRacStatus(s);
        }) || cleanedPassengers[0];

        const travelClass = normalized.class || (targetPassenger?.booking_status ? targetPassenger.booking_status.split('/')[0] : 'Unknown');

        // ── WL Type Extraction (4C301 / P1 fix) ─────────────────────────────────
        // IRCTC may return booking_status as raw "WAITLIST" (no subtype prefix).
        // We therefore search BOTH current_status and booking_status for a typed
        // WL prefix, covering all Indian Railways quota types.
        const WL_TYPE_REGEX = /\b(GNWL|TQWL|RLWL|PQWL|CKWL|RSWL)\b/i;
        const bookingStr = (targetPassenger?.booking_status || '').toUpperCase();
        const currentStr = (targetPassenger?.current_status || '').toUpperCase();

        // Search booking_status first, then current_status, then fallback by quota.
        const wlTypeMatchBkg = bookingStr.match(WL_TYPE_REGEX);
        const wlTypeMatchCur = currentStr.match(WL_TYPE_REGEX);
        // Derive from quota field as a last resort, but NEVER default to 'CNF' for a WL ticket.
        const wlTypeFallback = worstStatusType === 'RAC'
          ? 'RAC'
          : (normalized.quota === 'TQ' ? 'TQWL' : normalized.quota === 'RL' ? 'RLWL' : normalized.quota === 'PQ' ? 'PQWL' : 'GNWL');
        const wlType = (wlTypeMatchBkg?.[1] || wlTypeMatchCur?.[1] || wlTypeFallback).toUpperCase();
        // ─────────────────────────────────────────────────────────────────────────

        const wlPosition = minWLPos === 999 ? 0 : minWLPos;
        const quota = normalized.quota || (wlType === 'TQWL' ? 'TQ' : wlType === 'RLWL' ? 'RL' : wlType === 'PQWL' ? 'PQ' : 'GN');

        // Step 6: Fetch historical conversion pattern for the waitlisted passenger
        let historicalRate: number | null = null;
        try {
          // Phase 3: Use WL range-matching (±5 positions) instead of exact WL string match
          const { pnrHistoryService: pnrHist } = require('../services/pnrHistoryService');
          const historicalData = await pnrHist.getHistoricalDataForPrediction(
            normalized.source_code || normalized.source_name || '',
            normalized.destination_code || normalized.destination_name || '',
            targetPassenger?.current_status || targetPassenger?.booking_status || ''
          );
          historicalRate = (historicalData && historicalData.totalCount >= 3) ? historicalData.successRate : null;
        } catch (e) {}

        // Fetch learning aggregates and feedback drift
        let enrichmentContext: any = null;
        try {
          const { learningService } = require('../services/learningService');
          const routeVal = `${normalized.source_code || 'Unknown'}-${normalized.destination_code || 'Unknown'}`;
          const trainVal = normalized.train_no;
          
          const [routeAgg, trainAgg, quotaAgg, wlTypeAgg, feedbackDrift] = await Promise.all([
            learningService.getLearningAggregate('route', routeVal),
            learningService.getLearningAggregate('train', trainVal),
            learningService.getLearningAggregate('quota', quota),
            learningService.getLearningAggregate('wl_type', wlType),
            learningService.getFeedbackDrift()
          ]);

          const historicalData: any = {};
          if (trainAgg) {
            // ── Confidence Weighting (4C301) ──────────────────────────────────
            // sample_size < 5 → never reaches here (getLearningAggregate returns null).
            // For 5-20 samples: low confidence; 21-100: medium; >100: high.
            const trainConfidence = trainAgg.sampleSize > 100 ? 'HIGH' : trainAgg.sampleSize > 20 ? 'MEDIUM' : 'LOW';
            historicalData.train_quota_success_rate = `${trainAgg.successRate}% (based on ${trainAgg.sampleSize} bookings of Train ${trainVal}, confidence=${trainConfidence})`;
          }
          if (routeAgg) {
            const routeConfidence = routeAgg.sampleSize > 100 ? 'HIGH' : routeAgg.sampleSize > 20 ? 'MEDIUM' : 'LOW';
            historicalData.route_quota_success_rate = `${routeAgg.successRate}% (based on ${routeAgg.sampleSize} bookings from ${routeVal.replace('-', ' to ')}, confidence=${routeConfidence})`;
          }
          if (quotaAgg || wlTypeAgg) {
            const globalRate = wlTypeAgg?.successRate || quotaAgg?.successRate || 50;
            const globalCount = wlTypeAgg?.sampleSize || quotaAgg?.sampleSize || 10;
            const globalConfidence = globalCount > 100 ? 'HIGH' : globalCount > 20 ? 'MEDIUM' : 'LOW';
            historicalData.global_quota_success_rate = `${wlType} tickets have a global confirmation rate of ${globalRate}% (based on ${globalCount} samples, confidence=${globalConfidence})`;
          }

          enrichmentContext = {
            historical_data: historicalData,
            user_feedback_drift: {
              recent_discrepancies: feedbackDrift
            }
          };
        } catch (err: any) {
          winstonLogger.warn(`[PNR_CONTROLLER] Learning context enrichment failed: ${err.message}`);
        }

        try {
          const aiPrediction = await llmService.predictPNRConfirmation({
            pnr,
            train_no: normalized.train_no,
            passengers: cleanedPassengers,
            chart_status: normalized.chart_status,
            wl_type: wlType,
            wl_position: wlPosition,
            enrichmentContext
          });
          
          if (historicalRate !== null) {
            probability = `${historicalRate}%`;
            predictionText = historicalRate > 70 ? "Strong Chance (Historical)" : historicalRate > 40 ? "Medium Chance (Historical)" : "Low Chance (Historical)";
            advice = `Based on our learning engine, this specific waitlist confirms ${historicalRate}% of the time.`;
            predictionSource = "HISTORICAL_DB";
          } else {
            // ── Post-Gemini Heuristic Ceiling Check ────────────────────────
            // Compute the heuristic ceiling for this WL type+position.
            // If Gemini exceeds it by more than 15 points, clamp to ceiling + 5
            // to prevent over-confident outputs caused by contaminated context.
            const heuristicCeiling = (type: string, pos: number): number => {
              switch (type) {
                case 'GNWL': return pos <= 10 ? 88 : pos <= 20 ? 78 : pos <= 35 ? 62 : pos <= 60 ? 42 : 22;
                case 'PQWL': return pos <= 5 ? 55 : pos <= 10 ? 38 : pos <= 20 ? 22 : 12;
                case 'RLWL': return pos <= 8 ? 65 : pos <= 18 ? 45 : pos <= 30 ? 28 : 15;
                case 'TQWL': return pos <= 3 ? 22 : pos <= 8 ? 12 : 6;
                default:     return pos <= 15 ? 70 : pos <= 40 ? 45 : 20;
              }
            };

            const rawGeminiProb = parseInt(String(aiPrediction.probability).replace('%', ''), 10) || 50;
            const ceiling = worstStatusType === 'WL' ? heuristicCeiling(wlType, wlPosition) : 95;
            const CEILING_TOLERANCE = 15; // allow Gemini up to 15 points above heuristic ceiling

            let finalProb = rawGeminiProb;
            if (rawGeminiProb > ceiling + CEILING_TOLERANCE) {
              finalProb = ceiling + 5; // soft clamp
              winstonLogger.warn(`[PNR_PREDICTION_CAP] Gemini gave ${rawGeminiProb}% for ${wlType}/${wlPosition} (ceiling=${ceiling}). Clamped to ${finalProb}%.`);
            }
            // ─────────────────────────────────────────────────────────────────────

            probability = String(finalProb);
            predictionText = aiPrediction.prediction;
            advice = aiPrediction.advice;
            predictionSource = "GEMINI_FLASH";
          }
          // Phase 2: Capture AI plain-English explanation
          explanation = aiPrediction.explanation || '';
        } catch (err) {
          // ── WL-TYPE-AWARE HEURISTIC FALLBACK (Phase 4C08C / P0 & P1 Fix) ───────
          if (historicalRate !== null) {
            probability = `${historicalRate}%`;
            predictionText = historicalRate > 70 ? "Strong Chance (Historical)" : historicalRate > 40 ? "Medium Chance (Historical)" : "Low Chance (Historical)";
            predictionSource = "HISTORICAL_DB";
          } else if (worstStatusType === 'WL') {
            // Detect WL type from the target passenger's status string (P1 fix)
            const targetBookingStr = (targetPassenger?.booking_status || targetPassenger?.current_status || '').toUpperCase();
            const wlTypeMatch = targetBookingStr.match(/\b(GNWL|TQWL|RLWL|PQWL|CKWL|RSWL)\b/);
            const fallbackWlType = wlTypeMatch ? wlTypeMatch[1] : wlType;

            /**
             * Calibrated heuristics per WL quota type:
             *   GNWL  — General Waitlist: highest confirmation rate
             *   PQWL  — Pooled Quota WL: moderate, shared pool with other quotas
             *   RLWL  — Remote Location WL: lower than GNWL, depends on route
             *   TQWL  — Tatkal WL: almost never confirms (Tatkal quota is small)
             */
            const heuristicProb = (type: string, pos: number): number => {
              switch (type) {
                case 'GNWL':
                  if (pos <= 10) return 88;
                  if (pos <= 20) return 78;
                  if (pos <= 35) return 62;
                  if (pos <= 60) return 42;
                  return 22;
                case 'PQWL':
                  if (pos <= 5)  return 55;
                  if (pos <= 10) return 38;
                  if (pos <= 20) return 22;
                  return 12;
                case 'RLWL':
                  if (pos <= 8)  return 65;
                  if (pos <= 18) return 45;
                  if (pos <= 30) return 28;
                  return 15;
                case 'TQWL':
                  // Tatkal quota is tiny; rarely confirms
                  if (pos <= 3)  return 22;
                  if (pos <= 8)  return 12;
                  return 6;
                default:
                  // Unknown type — conservative generic table
                  if (pos <= 15) return 70;
                  if (pos <= 40) return 45;
                  return 20;
              }
            };

            const pct = heuristicProb(fallbackWlType, minWLPos);
            probability = `${pct}%`;
            predictionText = pct >= 70
              ? `Strong Chance (${fallbackWlType}/${minWLPos})`
              : pct >= 40
              ? `Moderate Chance (${fallbackWlType}/${minWLPos})`
              : `Low Chance (${fallbackWlType}/${minWLPos})`;
            predictionSource = "HEURISTIC_FALLBACK";
          } else {
            // RAC — almost always gets a berth
            probability = "92%";
            predictionText = "RAC (Seat Allocated, Berth Probable)";
            predictionSource = "HEURISTIC_FALLBACK";
          }
          advice = historicalRate !== null
            ? `Based on our learning engine, this specific waitlist confirms ${historicalRate}% of the time.`
            : "Keep monitoring — chart preparation updates status 4-6 hours before departure.";

          // Deterministic explanation for offline/fallback mode (P1 message fix)
          const routeStr = `${normalized.source_code || 'Origin'} to ${normalized.destination_code || 'Destination'}`;
          explanation = historicalRate !== null
            ? `Historical records on the ${routeStr} route indicate a ${historicalRate}% confirmation rate for ${wlType} tickets at position ${wlPosition}.`
            : worstStatusType === 'RAC'
            ? `RAC allocations automatically guarantee travel on the train, with a ${probability} likelihood of upgrading to a full berth during chart preparation.`
            : `${wlType} tickets at position ${minWLPos} on Train ${normalized.train_no} (${routeStr}) have a calibrated ${probability} confirmation probability under ${quota} quota rules. Charting updates final allocations 4-6 hours prior to departure.`;
        }

        if (!isChartPrepared && isPartiallyConfirmed) {
          predictionText = "Partially Confirmed";
          advice = `Partially Confirmed. ${cnfCount} of ${totalPassengers} passengers are confirmed. Prediction for waitlist: ${probability} chance of confirmation.`;
        }

        // Save prediction log
        try {
          const { learningService } = require('../services/learningService');
          const numericProb = parseInt(String(probability).replace('%', ''), 10) || 50;
          await learningService.logPrediction(
            pnr,
            normalized.train_no,
            `${normalized.source_code || 'Unknown'}-${normalized.destination_code || 'Unknown'}`,
            quota,
            travelClass,
            wlType,
            wlPosition,
            numericProb,
            predictionSource
          );
        } catch (logErr: any) {
          winstonLogger.error(`[PNR_PREDICTION_LOG_FAIL] Error saving prediction log: ${logErr.message}`);
        }
      }

      // Phase 1: Compute numeric prob for confidence label mapping
      const numericProb = showPrediction
        ? (parseInt(String(probability).replace('%', ''), 10) || null)
        : null;

      const prediction: any = {
        text: predictionText,
        confidence_label: isChartPrepared
          ? (isPartiallyConfirmed ? `Partially Confirmed — ${cnfCount}/${totalPassengers} Confirmed` : (worstStatusType === 'RAC' ? 'RAC Seat Allocated' : worstStatusType === 'WL' ? 'Waitlist Finalized' : 'Confirmed — Enjoy Your Journey'))
          : (isPartiallyConfirmed ? `Partially Confirmed — ${cnfCount}/${totalPassengers} Confirmed` : this.getConfidenceLabel(numericProb, worstStatusType)),
        advice,
        ...(explanation ? { explanation } : {}),
        worst_pos: minWLPos === 999 ? null : minWLPos
      };

      if (showPrediction) {
        prediction.probability = probability;
      }

      const cleanResponse = {
        success: true,
        data_source: 'live',
        data: {
          pnr: pnr,
          train_name: normalized.train_name,
          train_no: normalized.train_no,
          journey_date: normalized.journey_date,
          source: await stationService.getStationName(normalized.source_code, normalized.source_name || 'N/A'),
          destination: await stationService.getStationName(normalized.destination_code, normalized.destination_name || 'N/A'),
          chart_status: normalized.chart_status,
          boarding_station: normalized.boarding_station || "N/A",
          passengers: cleanedPassengers,
          prediction,
          twitter_complaint_url: trainService.generateTwitterUrl(normalized.train_no, "N/A", "Journey Issue")
        }
      };

      // Save to PNR history and metrics
      try {
        const { learningService } = require('../services/learningService');
        await learningService.logPnrCheck(
          pnr,
          cleanedPassengers[0]?.booking_status || 'Unknown',
          cleanedPassengers[0]?.current_status || 'Unknown',
          cleanResponse.data.chart_status !== 'Chart Not Prepared'
        );
        await learningService.trackApiUsage('pnr');
        winstonLogger.info(`[PNR_LEARNING] Logged learning data for PNR: ${pnr}`);
      } catch (saveError: any) {
        winstonLogger.error(`[PNR_LEARNING] Failed to log learning for PNR: ${pnr}: ${saveError.message}`);
      }

      // LOG PARSED OUTPUT
      winstonLogger.info(`[PNR PARSED OUTPUT] pnr=${pnr}: ${JSON.stringify(cleanResponse)}`);
      res.status(200).json(cleanResponse);
    } catch (err: any) {
      winstonLogger.error(`PNR Controller Error: ${err.message}`);
      return res.status(200).json(this.buildPnrFallback(pnr));
    }
  }

  async track(req: Request, res: Response) {
    const { pnr, session_id, current_status, journey_date } = req.body;
    if (!pnr || !session_id) return res.status(400).json({ success: false, error: 'Missing PNR or Session ID' });

    const result = await pnrTrackingService.trackPnr({
      pnr_number: pnr,
      session_id,
      current_status,
      journey_date
    });

    res.status(result.success ? 200 : 500).json(result);
  }

  async listTracked(req: Request, res: Response) {
    const { sessionId } = req.params;
    const list = await pnrTrackingService.listBySession(sessionId);

    // Auto-clear flags when listing (user has seen them)
    await pnrTrackingService.clearChangeFlag(sessionId);

    res.status(200).json({ success: true, data: list });
  }

  async untrack(req: Request, res: Response) {
    const { pnr, sessionId } = req.params;
    const { error } = await require('../config/supabase').supabase
      .from('pnr_tracking')
      .delete()
      .eq('pnr_number', pnr)
      .eq('session_id', sessionId);

    res.status(!error ? 200 : 500).json({ success: !error });
  }

  async upgrade(req: Request, res: Response) {
    const userId = req.headers['x-user-id'] as string;
    if (!userId) {
      return res.status(401).json({ success: false, error: 'Unauthorized' });
    }

    const { authService } = require('../services/authService');
    const hasPro = await authService.userHasActiveProSubscription(userId);
    if (!hasPro) {
      return res.status(403).json({ success: false, error: 'Active PRO subscription required' });
    }

    const { pnr } = req.params;
    winstonLogger.info(`[PNR_UPGRADE] Request for PNR: ${pnr} by user ${userId}`);

    const { error } = await require('../config/supabase').supabase
      .from('pnr_tracking')
      .update({ is_pro: true })
      .eq('pnr_number', pnr);

    if (error) {
      winstonLogger.error(`[PNR_UPGRADE] Error: ${error.message}`);
      return res.status(500).json({ success: false, error: 'Database update failed' });
    }

    res.status(200).json({ success: true, message: 'Upgraded to PRO' });
  }
}

export const pnrController = new PnrController();
